// Simulated sales data (as if generated by Python/Scikit-learn ML model)
// In production, this would come from your Python backend

export interface SalesRecord {
  month: string;
  actual: number;
  predicted: number;
  variance: number;
  variancePercent: number;
}

export interface KPIData {
  totalActualSales: number;
  totalPredictedSales: number;
  overallVariance: number;
  overallVariancePercent: number;
  accuracy: number;
  mape: number; // Mean Absolute Percentage Error
}

// Generate realistic sales data with seasonal patterns
export const generateSalesData = (): SalesRecord[] => {
  const months = [
    'Jan 2024', 'Feb 2024', 'Mar 2024', 'Apr 2024', 'May 2024', 'Jun 2024',
    'Jul 2024', 'Aug 2024', 'Sep 2024', 'Oct 2024', 'Nov 2024', 'Dec 2024',
    'Jan 2025', 'Feb 2025', 'Mar 2025', 'Apr 2025', 'May 2025', 'Jun 2025'
  ];

  // Base sales with seasonal variation
  const baseSales = [
    85000, 78000, 92000, 98000, 105000, 115000,
    108000, 112000, 125000, 135000, 155000, 180000,
    95000, 88000, 102000, 110000, 118000, 128000
  ];

  return months.map((month, index) => {
    const actual = baseSales[index];
    // Simulated ML prediction with some variance
    const predictionError = (Math.random() - 0.5) * 0.15; // ±7.5% error
    const predicted = Math.round(actual * (1 + predictionError));
    const variance = actual - predicted;
    const variancePercent = ((variance / predicted) * 100);

    return {
      month,
      actual,
      predicted,
      variance,
      variancePercent: Math.round(variancePercent * 100) / 100
    };
  });
};

export const calculateKPIs = (data: SalesRecord[]): KPIData => {
  const totalActualSales = data.reduce((sum, record) => sum + record.actual, 0);
  const totalPredictedSales = data.reduce((sum, record) => sum + record.predicted, 0);
  const overallVariance = totalActualSales - totalPredictedSales;
  const overallVariancePercent = (overallVariance / totalPredictedSales) * 100;
  
  // Calculate MAPE (Mean Absolute Percentage Error)
  const mape = data.reduce((sum, record) => {
    return sum + Math.abs((record.actual - record.predicted) / record.actual);
  }, 0) / data.length * 100;

  const accuracy = 100 - mape;

  return {
    totalActualSales,
    totalPredictedSales,
    overallVariance,
    overallVariancePercent: Math.round(overallVariancePercent * 100) / 100,
    accuracy: Math.round(accuracy * 100) / 100,
    mape: Math.round(mape * 100) / 100
  };
};

// DAX-like calculations for Power BI reference
export const daxFormulas = {
  variance: 'Variance = SUM(Sales[Actual]) - SUM(Sales[Predicted])',
  variancePercent: 'Variance % = DIVIDE([Variance], SUM(Sales[Predicted]), 0) * 100',
  mape: 'MAPE = AVERAGEX(Sales, ABS(Sales[Actual] - Sales[Predicted]) / Sales[Actual]) * 100',
  accuracy: 'Forecast Accuracy = 100 - [MAPE]',
  ytdActual: 'YTD Actual = TOTALYTD(SUM(Sales[Actual]), Dates[Date])',
  ytdPredicted: 'YTD Predicted = TOTALYTD(SUM(Sales[Predicted]), Dates[Date])'
};

// Export to CSV for Power BI
export const exportToCSV = (data: SalesRecord[]): string => {
  const headers = ['Month', 'Actual_Sales', 'Predicted_Sales', 'Variance', 'Variance_Percent'];
  const rows = data.map(record => 
    [record.month, record.actual, record.predicted, record.variance, record.variancePercent].join(',')
  );
  return [headers.join(','), ...rows].join('\n');
};

export const downloadCSV = (data: SalesRecord[], filename: string = 'sales_forecast_data.csv') => {
  const csv = exportToCSV(data);
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
